# Site settings
title: Nick Aversano
email: nospamnick+at+nickaversano.com
description: >
  Hi, I'm Nick. I create websites, develop apps, shoot videos, design things, and make games.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nickaversano.com" # the base hostname & protocol for your site
twitter_username: nickaversano
github_username:  nickaversano
spotify_username: 121907576

# Build settings
sass:
  sass_dir: _sass
markdown: kramdown
permalink: /:title/
collections:
  projects:
    output: true
    permalink: /:title/
